### ISSUE TITLE
'getComputedStyle' on 'Window', isn't "window" with lowercase?

### ISSUE THREAD

**Issue by anaibol** [liriliri/eruda#1] opened 2016-05-09 19:46 UTC
Amazing work, man! Thank you! This was something missing..
Trying it with React stack.

![selection_033](https://cloud.githubusercontent.com/assets/3210177/15125859/5b73f022-162f-11e6-9055-f76b0844da8a.png)

**Comment by surunzi** [comment] 2016-05-10 02:37
Judging from the error message, it is not caused by misspelling, probably the dom node currently viewing is deleted. Can you use the uncompressed one to see which line exactly is causing the problem? Since there are several places using `getComputedStyle` api, including some third party libs. Thanks:)

**Comment by leo108** [comment] 2016-05-10 06:21
same problem, the error line is `3010`, relative code is

	Draggabilly.prototype._getPosition = function() {
	  var style = getComputedStyle( this.element ); // this line
	  var x = this._getPositionCoord( style.left, 'width' );
	  var y = this._getPositionCoord( style.top, 'height' );
	  // clean up 'auto' or other non-integer values
	  this.position.x = isNaN( x ) ? 0 : x;
	  this.position.y = isNaN( y ) ? 0 : y;

	  this._addTransformPosition( style );
	};

**Comment by surunzi** [comment] 2016-05-10 07:08
The tool will append a dom node as container to body when initialized, Looks like the dom is somehow erased afterwards. Are you guys using some frameworks that will rewrite the whole body content? 

I'm planning on moving it to outside of body, hopefully it's going to solve this problem:)

**Comment by leo108** [comment] 2016-05-10 07:39
Put the script label at the end of document should be OK, I came across this problem just because I put it in the `head` tag

**Comment by surunzi** [comment] 2016-05-10 08:56
@leo108 Container element is now appended to html tag, should be ok to put it in `head` tag now.
@anaibol Did you put the script inside `head` tag too?

**Comment by anaibol** [comment] 2016-05-10 09:09
I am executing the script on componentDidMount of React.
I don't have this error now, but Eruda is replacing all my DOM.
Before
![selection_034](https://cloud.githubusercontent.com/assets/3210177/15141288/97e51354-169f-11e6-845a-2d6316b9ef27.png)
After
![selection_035](https://cloud.githubusercontent.com/assets/3210177/15141300/ae512ee8-169f-11e6-8bcd-42562855a85b.png)

**Comment by surunzi** [comment] 2016-05-10 09:26
Oh, I haven't used this tool in a full-react application yet. Will try to figure out a way to solve it later. Thanks for reporting the issue.

**Comment by anaibol** [comment] 2016-05-10 09:39
Cool! I was thinking, it would be interesting also to submit it to a CDN like Jsdelivr, because you want to async and condicionally load the debugger, it should be easier to load it from an external CDN instead of making maybe a webpack entrypoint only for the debugger.

**Comment by surunzi** [comment] 2016-07-03 10:01
@anaibol It's on Jsdelivr now, and thanks for your advice. https://cdn.jsdelivr.net/eruda/1.0.0/eruda.min.js

**Closed** 2016-07-03 10:16 UTC
