### ISSUE TITLE
Editing page elements

### ISSUE THREAD

**Issue by hjyoung1** [liriliri/eruda#110] opened 2019-07-24 20:32 UTC
It would be great if editing page elements like (html + css) become possible.
Currently with edit page snippet only text is allowed to edited.
Thanks for creating and actively working on this project.

**Comment by surunzi** [comment] 2019-07-27 12:14
Duplicate of #25

**Closed by surunzi** 2019-07-27 12:14 UTC

**Comment by NguyenThanh1995** [comment] 2021-01-14 09:35
I have updated it so you can fix all CSS including @media, styles, @keyframes ... I'm waiting for the author to merge it. 😄 You are the reason I made this upgrade
