### ISSUE TITLE
iOS报错

### ISSUE THREAD

**Issue by frontendnote** [liriliri/eruda#112] opened 2019-07-30 08:01 UTC
[查看异常信息详情](https://sentry.io/share/issue/4163f1b27fa44db2a0e67d94ea6dbbed/)
``` js
TypeError
et is not a function. (In 'et("local")', 'et' is an instance of Object)
```
``` js
{snip} A(r)&&(r=null),r}}(),t)}}();t.LocalStore=O.LocalStore=(S=et("local"),lt.extend({"initialize":function LocalStore(e,t){this._name=e,t=t||{};v {snip}
```

**Comment by surunzi** [comment] 2019-08-02 10:15
#108

**Comment by surunzi** [comment] 2019-08-02 10:16
Duplicate of #108

**Closed** 2019-08-02 10:17 UTC
